platform :ios, '13.0'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['LD_NO_PIE'] = 'NO'
    end
  end
end
  
target 'Cartoons' do
  use_frameworks!
  inhibit_all_warnings!
  
  pod 'R.swift'
  pod 'SwiftLint'
  pod 'SnapKit'
  pod 'SwiftFormat/CLI'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Kingfisher'
  
end

target 'CartoonsTests' do
  use_frameworks!
  inhibit_all_warnings!
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
end

